# pwd : 192.168.3.217  /data/filebeat
# execute : filebeat.sh -c /data/filebeat/online_combine_filebeat.yml &

filebeat.prospectors:
- input_type: log
  paths:
    - /root/corgi/logs/online_combine.log
  json.message_key: event
  json.keys_under_root: true
  document_type: combine

output.logstash:
  hosts: ["192.168.1.188:5058"]
      # output.console:
      # pretty: true
logging.level: warning
logging.to_files: true
logging.syslog: false
logging.files:
  path: /var/log/filebeat
  name: combine.log
  keepfiles: 7
