filebeat.prospectors:
- input_type: log
  paths:
    - /root/corgi/logs/push_bandwidth.log
  json.message_key: event
  json.keys_under_root: true
  document_type: bandwidth

output.logstash:
  hosts: ["192.168.1.188:5059"]
      # output.console:
      #       # pretty: true
logging.level: warning
logging.to_files: true
logging.syslog: false
logging.files:
  path: /var/log/filebeat
  name: push_bandwidth.log
  keepfiles: 7
