filebeat.prospectors:
- input_type: log
  paths:
    - /root/corgi/logs/task_vod_push_delete.log
  json.message_key: event
  json.keys_under_root: true
  document_type: task_push_delete

output.logstash:
  hosts: ["192.168.1.188:5054"]
          # output.console:
          # pretty: true
logging.level: warning
logging.to_files: true
logging.syslog: false
logging.files:
  path: /var/log/filebeat
  name: push_delete.log
  keepfiles: 7

